import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  RefreshControl,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Modal,
} from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import { Calendar, Clock, CheckCircle2, PlayCircle, Trash2, AlertCircle, Sparkles, X } from 'lucide-react-native';
import ScreenWrapper from '../../components/common/ScreenWrapper';
import Header from '../../components/common/Header';
import ExamLiveNav from '../../components/common/ExamLiveNav';
import api from '../../services/api';

export default function SlotBookingScreen() {
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  
  const [subjects, setSubjects] = useState([]);
  const [bookings, setBookings] = useState([]);
  
  // Booking modal state
  const [bookingModalVisible, setBookingModalVisible] = useState(false);
  const [selectedSubject, setSelectedSubject] = useState(null);
  const [availableSlots, setAvailableSlots] = useState([]);
  const [loadingSlots, setLoadingSlots] = useState(false);
  const [selectedDate, setSelectedDate] = useState(null);
  const [selectedTime, setSelectedTime] = useState(null);
  const [submitting, setSubmitting] = useState(false);

  const fetchData = useCallback(async () => {
    try {
      const [subjRes, bookRes] = await Promise.all([
        api.get('/api/learning/subjects').catch(() => ({ data: [] })),
        api.get('/api/learning/slots').catch(() => ({ data: [] })),
      ]);
      setSubjects(subjRes.data || []);
      setBookings(bookRes.data || []);
    } catch (err) {
      console.error('Error fetching slot bookings:', err);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const onRefresh = () => {
    setRefreshing(true);
    fetchData();
  };

  const handleOpenBookingModal = async (subject) => {
    setSelectedSubject(subject);
    setSelectedDate(null);
    setSelectedTime(null);
    setBookingModalVisible(true);
    setLoadingSlots(true);

    try {
      const res = await api.get(`/api/learning/subjects/${subject.id}/slots/available`);
      const slots = res.data || [];
      setAvailableSlots(slots);
      if (slots.length > 0) {
        setSelectedDate(slots[0].date);
      }
    } catch (err) {
      console.error('Error fetching available slots:', err);
      Alert.alert('Notice', 'Could not load exam slots for this subject.');
      setAvailableSlots([]);
    } finally {
      setLoadingSlots(false);
    }
  };

  const handleConfirmBooking = async () => {
    if (!selectedDate || !selectedTime || !selectedSubject) {
      Alert.alert('Selection Required', 'Please choose a valid exam date and time slot.');
      return;
    }

    setSubmitting(true);
    try {
      await api.post(`/api/learning/subjects/${selectedSubject.id}/slots/book`, {
        slot_date: selectedDate,
        slot_time: selectedTime,
      });
      Alert.alert('Success', 'Your proctored exam slot has been confirmed!');
      setBookingModalVisible(false);
      fetchData();
    } catch (err) {
      const msg = err.response?.data?.detail || 'Booking failed. You may already have an active booking for this subject.';
      Alert.alert('Booking Error', msg);
    } finally {
      setSubmitting(false);
    }
  };

  const handleCancelBooking = async (bookingId) => {
    Alert.alert(
      'Cancel Exam Slot',
      'Are you sure you want to cancel this booking? This action cannot be undone.',
      [
        { text: 'Keep Slot', style: 'cancel' },
        {
          text: 'Cancel Slot',
          style: 'destructive',
          onPress: async () => {
            try {
              await api.delete(`/api/learning/slots/${bookingId}`);
              Alert.alert('Cancelled', 'Exam slot cancelled.');
              fetchData();
            } catch (err) {
              const msg = err.response?.data?.detail || 'Could not cancel booking.';
              Alert.alert('Error', msg);
            }
          },
        },
      ]
    );
  };

  // Launch proctored exam securely inside Expo WebBrowser
  const handleLaunchExam = async (booking) => {
    if (!booking.assessment_link) {
      Alert.alert(
        'Assessment Pending',
        'The examination link is being generated by the proctor engine. Please check back when your slot window opens.'
      );
      return;
    }

    try {
      await WebBrowser.openBrowserAsync(booking.assessment_link, {
        toolbarColor: '#0f172a',
        controlsColor: '#818cf8',
        enableBarCollapsing: false,
        showTitle: true,
      });
    } catch (err) {
      Alert.alert('Error', 'Could not open secure proctored browser window.');
    }
  };

  if (loading) {
    return (
      <ScreenWrapper>
        <Header title="Proctored Exams" subtitle="Dynamic Slot Booking & Launch" />
        <ExamLiveNav activeTab="slots" />
        <View style={styles.centerContainer}>
          <ActivityIndicator size="large" color="#4f46e5" />
          <Text style={styles.loadingText}>Loading exam schedules...</Text>
        </View>
      </ScreenWrapper>
    );
  }

  // Group active vs past bookings
  const activeBookings = bookings.filter((b) => b.status === 'confirmed');
  const pastBookings = bookings.filter((b) => b.status !== 'confirmed');

  return (
    <ScreenWrapper>
      <Header title="Proctored Exams" subtitle="Dynamic Slot Booking & Launch" />
      <ExamLiveNav activeTab="slots" />
      <ScrollView
        contentContainerStyle={styles.content}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#4f46e5" />}
      >
        {/* Info Banner */}
        <View style={styles.infoBanner}>
          <Sparkles size={20} color="#818cf8" />
          <Text style={styles.infoBannerText}>
            Select a subject to reserve a proctored exam window. When your slot starts, tap &quot;Launch Proctored Exam&quot; to open the secure webcam verification engine inside the in-app browser.
          </Text>
        </View>

        {/* Section: Book a New Slot */}
        <Text style={styles.sectionTitle}>Available Subjects for Examination</Text>
        {subjects.length === 0 ? (
          <View style={styles.emptyCard}>
            <Text style={styles.emptyTitle}>No Subjects Assigned</Text>
            <Text style={styles.emptySubtext}>You have no subjects assigned for examination booking.</Text>
          </View>
        ) : (
          subjects.map((subj) => {
            const hasConfirmed = activeBookings.some((b) => b.subject_id === subj.id);
            return (
              <View key={subj.id} style={styles.subjectRow}>
                <View style={{ flex: 1 }}>
                  <View style={styles.badgeRow}>
                    <Text style={styles.subjCode}>{subj.code || `SUB-${subj.id}`}</Text>
                    {hasConfirmed ? (
                      <View style={styles.bookedTag}>
                        <CheckCircle2 size={12} color="#10b981" />
                        <Text style={styles.bookedTagText}>SLOT RESERVED</Text>
                      </View>
                    ) : null}
                  </View>
                  <Text style={styles.subjName}>{subj.name}</Text>
                </View>

                {!hasConfirmed ? (
                  <TouchableOpacity
                    style={styles.bookBtn}
                    onPress={() => handleOpenBookingModal(subj)}
                  >
                    <Calendar size={15} color="#ffffff" />
                    <Text style={styles.bookBtnText}>Book Slot</Text>
                  </TouchableOpacity>
                ) : null}
              </View>
            );
          })
        )}

        {/* Section: Active Bookings */}
        <Text style={[styles.sectionTitle, { marginTop: 28 }]}>Confirmed Exam Reservations</Text>
        {activeBookings.length === 0 ? (
          <View style={styles.emptyCard}>
            <Calendar size={32} color="#64748b" style={{ marginBottom: 10 }} />
            <Text style={styles.emptyTitle}>No Confirmed Reservations</Text>
            <Text style={styles.emptySubtext}>Book an exam slot above to unlock your proctored assessment credentials.</Text>
          </View>
        ) : (
          activeBookings.map((b) => {
            const subjName = subjects.find((s) => s.id === b.subject_id)?.name || `Subject #${b.subject_id}`;
            return (
              <View key={b.id} style={styles.bookingCard}>
                <View style={styles.bookingHeaderRow}>
                  <Text style={styles.bookingRef}>{b.booking_reference}</Text>
                  <View style={styles.activePill}>
                    <Text style={styles.activePillText}>CONFIRMED</Text>
                  </View>
                </View>

                <Text style={styles.bookingSubject}>{subjName}</Text>

                <View style={styles.bookingMetaRow}>
                  <View style={styles.metaItem}>
                    <Calendar size={16} color="#818cf8" />
                    <Text style={styles.metaText}>{b.slot_date}</Text>
                  </View>
                  <View style={styles.metaItem}>
                    <Clock size={16} color="#818cf8" />
                    <Text style={styles.metaText}>{b.slot_time}</Text>
                  </View>
                </View>

                {/* Launch & Cancel Actions */}
                <View style={styles.actionFooter}>
                  <TouchableOpacity
                    style={[styles.launchBtn, !b.assessment_link && styles.launchBtnDisabled]}
                    onPress={() => handleLaunchExam(b)}
                  >
                    <PlayCircle size={18} color="#ffffff" />
                    <Text style={styles.launchBtnText}>Launch Proctored Exam</Text>
                  </TouchableOpacity>

                  <TouchableOpacity
                    style={styles.deleteBtn}
                    onPress={() => handleCancelBooking(b.id)}
                  >
                    <Trash2 size={18} color="#ef4444" />
                  </TouchableOpacity>
                </View>
              </View>
            );
          })
        )}

        {/* Section: Past Bookings */}
        {pastBookings.length > 0 ? (
          <View style={{ marginTop: 28 }}>
            <Text style={styles.sectionTitle}>History & Past Bookings</Text>
            {pastBookings.map((pb) => (
              <View key={pb.id} style={styles.pastCard}>
                <View style={{ flex: 1 }}>
                  <Text style={styles.pastRef}>{pb.booking_reference}</Text>
                  <Text style={styles.pastDate}>
                    {pb.slot_date} at {pb.slot_time}
                  </Text>
                </View>
                <View style={[styles.pastStatusTag, pb.status === 'completed' ? styles.statusCompleted : styles.statusCancelled]}>
                  <Text style={styles.pastStatusText}>{pb.status.toUpperCase()}</Text>
                </View>
              </View>
            ))}
          </View>
        ) : null}

        {/* Modal: Slot Booking Picker */}
        <Modal visible={bookingModalVisible} animationType="fade" transparent={true}>
          <View style={styles.modalOverlay}>
            <View style={styles.modalCard}>
              <View style={styles.modalHeader}>
                <View>
                  <Text style={styles.modalSub}>RESERVE SLOT</Text>
                  <Text style={styles.modalTitle}>{selectedSubject?.name}</Text>
                </View>
                <TouchableOpacity onPress={() => setBookingModalVisible(false)} style={styles.closeIcon}>
                  <X size={20} color="#0f172a" />
                </TouchableOpacity>
              </View>

              {loadingSlots ? (
                <View style={styles.modalLoading}>
                  <ActivityIndicator size="large" color="#4f46e5" />
                  <Text style={styles.loadingText}>Querying real exam windows...</Text>
                </View>
              ) : availableSlots.length === 0 ? (
                <View style={styles.emptyCard}>
                  <AlertCircle size={32} color="#f59e0b" style={{ marginBottom: 10 }} />
                  <Text style={styles.emptyTitle}>No Windows Configured</Text>
                  <Text style={styles.emptySubtext}>
                    There are no open examination dates configured for this subject at this time.
                  </Text>
                </View>
              ) : (
                <ScrollView style={{ maxHeight: 350 }}>
                  <Text style={styles.pickerLabel}>1. Select Date Window</Text>
                  <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.dateScroll}>
                    {availableSlots.map((slotObj) => {
                      const isSelected = selectedDate === slotObj.date;
                      return (
                        <TouchableOpacity
                          key={slotObj.date}
                          style={[styles.datePill, isSelected && styles.datePillSelected]}
                          onPress={() => {
                            setSelectedDate(slotObj.date);
                            setSelectedTime(null);
                          }}
                        >
                          <Text style={[styles.datePillText, isSelected && styles.datePillTextSelected]}>
                            {slotObj.date}
                          </Text>
                        </TouchableOpacity>
                      );
                    })}
                  </ScrollView>

                  <Text style={[styles.pickerLabel, { marginTop: 16 }]}>2. Select Time Slot</Text>
                  {(() => {
                    const activeDateObj = availableSlots.find((s) => s.date === selectedDate);
                    const times = activeDateObj?.times || [];
                    if (times.length === 0) {
                      return <Text style={styles.emptySubtext}>No time slots on this date.</Text>;
                    }
                    return (
                      <View style={styles.timesGrid}>
                        {times.map((t) => {
                          const isSelected = selectedTime === t;
                          return (
                            <TouchableOpacity
                              key={t}
                              style={[styles.timePill, isSelected && styles.timePillSelected]}
                              onPress={() => setSelectedTime(t)}
                            >
                              <Clock size={14} color={isSelected ? '#ffffff' : '#818cf8'} />
                              <Text style={[styles.timePillText, isSelected && styles.timePillTextSelected]}>
                                {t}
                              </Text>
                            </TouchableOpacity>
                          );
                        })}
                      </View>
                    );
                  })()}
                </ScrollView>
              )}

              <View style={styles.modalActions}>
                <TouchableOpacity
                  style={[
                    styles.confirmBtn,
                    (!selectedDate || !selectedTime || submitting) && styles.confirmBtnDisabled,
                  ]}
                  disabled={!selectedDate || !selectedTime || submitting}
                  onPress={handleConfirmBooking}
                >
                  {submitting ? (
                    <ActivityIndicator size="small" color="#ffffff" />
                  ) : (
                    <Text style={styles.confirmBtnText}>Confirm Reservation</Text>
                  )}
                </TouchableOpacity>
              </View>
            </View>
          </View>
        </Modal>
      </ScrollView>
    </ScreenWrapper>
  );
}

const styles = StyleSheet.create({
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    color: '#475569',
    marginTop: 12,
    fontSize: 15,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  infoBanner: {
    backgroundColor: 'rgba(79, 70, 229, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.4)',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 24,
  },
  infoBannerText: {
    flex: 1,
    color: '#334155',
    fontSize: 13,
    lineHeight: 19,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 12,
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 6,
  },
  emptySubtext: {
    fontSize: 13,
    color: '#475569',
    textAlign: 'center',
    lineHeight: 18,
  },
  subjectRow: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  subjCode: {
    color: '#818cf8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  bookedTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  bookedTagText: {
    color: '#10b981',
    fontSize: 10,
    fontWeight: '800',
  },
  subjName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  bookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#4f46e5',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  bookBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  bookingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.3)',
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  bookingHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  bookingRef: {
    color: '#818cf8',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  activePill: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  activePillText: {
    color: '#10b981',
    fontSize: 10,
    fontWeight: '800',
  },
  bookingSubject: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 12,
  },
  bookingMetaRow: {
    flexDirection: 'row',
    gap: 18,
    marginBottom: 18,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '600',
  },
  actionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.06)',
    paddingTop: 14,
  },
  launchBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#10b981',
    paddingVertical: 12,
    borderRadius: 12,
  },
  launchBtnDisabled: {
    backgroundColor: '#3b82f6',
  },
  launchBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  deleteBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  pastCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
    opacity: 0.8,
  },
  pastRef: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '700',
  },
  pastDate: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  pastStatusTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusCompleted: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  statusCancelled: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
  },
  pastStatusText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#475569',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.15)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    paddingBottom: 14,
  },
  modalSub: {
    color: '#818cf8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  modalTitle: {
    color: '#0f172a',
    fontSize: 19,
    fontWeight: '800',
    marginTop: 2,
  },
  closeIcon: {
    padding: 6,
  },
  modalLoading: {
    padding: 40,
    alignItems: 'center',
  },
  pickerLabel: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
  },
  dateScroll: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  datePill: {
    backgroundColor: '#FAF7F2',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  datePillSelected: {
    backgroundColor: '#4f46e5',
    borderColor: '#818cf8',
  },
  datePillText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '600',
  },
  datePillTextSelected: {
    color: '#ffffff',
    fontWeight: '700',
  },
  timesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  timePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FAF7F2',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  timePillSelected: {
    backgroundColor: '#4f46e5',
    borderColor: '#818cf8',
  },
  timePillText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '600',
  },
  timePillTextSelected: {
    color: '#ffffff',
    fontWeight: '700',
  },
  modalActions: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    paddingTop: 16,
  },
  confirmBtn: {
    backgroundColor: '#10b981',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  confirmBtnDisabled: {
    backgroundColor: '#F1F5F9',
  },
  confirmBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
});
