import os
import uuid
import hmac
import hashlib
import logging
import requests
from datetime import datetime
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, HTTPException, Body
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("exam_engine_stub")

app = FastAPI(
    title="Stub Examination Engine",
    description="Standalone external simulation of the Examination Engine per SRP integration contract.",
    version="1.0.0"
)

# In-memory store decoupling stub state from SRP database
stub_sessions: Dict[str, Dict[str, Any]] = {}

SRP_WEBHOOK_SECRET = os.getenv("EXAM_ENGINE_WEBHOOK_SECRET", "skillforge-exam-engine-secret-2026")
DEFAULT_SRP_WEBHOOK_BASE = os.getenv("SRP_WEBHOOK_BASE_URL", "http://localhost:8000/api/webhooks/exam-engine")

class SlotBookingRequest(BaseModel):
    booking_reference: str
    student_id: int
    student_name: str
    student_email: str
    registration_number: Optional[str] = None
    subject_id: int
    subject_code: str
    subject_name: str
    level: str
    slot_date: str
    slot_time: str
    slot_datetime: Optional[str] = None
    webhook_callback_url: Optional[str] = None

class SlotBookingResponse(BaseModel):
    success: bool
    booking_reference: str
    exam_engine_session_ref: str
    assessment_link: str
    link_status: str
    message: str

class TriggerResultRequest(BaseModel):
    booking_reference: str
    score: float = 85.0
    pass_fail: str = "PASS"
    level: Optional[str] = "District"
    webhook_url: Optional[str] = None

@app.get("/")
def health_check():
    return {"status": "ok", "service": "Stub Examination Engine", "sessions_count": len(stub_sessions)}

@app.post("/api/v1/exam-engine/slots/book", response_model=SlotBookingResponse)
def book_slot(req: SlotBookingRequest):
    """
    Receives slot booking from SRP, confirms slot and returns mock assessment link.
    """
    session_ref = f"EXM-SESS-{uuid.uuid4().hex[:8].upper()}"
    assessment_link = f"https://exam.skillforge.engine/assess/{session_ref}"

    session_data = {
        "booking_reference": req.booking_reference,
        "exam_engine_session_ref": session_ref,
        "assessment_link": assessment_link,
        "student_id": req.student_id,
        "student_name": req.student_name,
        "student_email": req.student_email,
        "subject_id": req.subject_id,
        "subject_code": req.subject_code,
        "subject_name": req.subject_name,
        "level": req.level,
        "slot_date": req.slot_date,
        "slot_time": req.slot_time,
        "webhook_callback_url": req.webhook_callback_url or DEFAULT_SRP_WEBHOOK_BASE,
        "status": "confirmed",
        "created_at": datetime.utcnow().isoformat()
    }

    stub_sessions[req.booking_reference] = session_data
    stub_sessions[session_ref] = session_data

    logger.info(f"Stub Engine booked slot for ref '{req.booking_reference}' -> session '{session_ref}'")

    return SlotBookingResponse(
        success=True,
        booking_reference=req.booking_reference,
        exam_engine_session_ref=session_ref,
        assessment_link=assessment_link,
        link_status="confirmed",
        message="Slot confirmed and link generated by Stub Exam Engine"
    )

@app.post("/api/v1/exam-engine/slots/cancel")
def cancel_slot(payload: Dict[str, Any] = Body(...)):
    ref = payload.get("exam_engine_session_ref")
    if ref in stub_sessions:
        stub_sessions[ref]["status"] = "cancelled"
    return {"success": True, "message": "Slot cancelled"}

@app.post("/api/v1/exam-engine/stub/trigger-link-ready")
def trigger_link_ready(booking_reference: str):
    """
    Simulates sending an asynchronous 'link-ready' webhook back to SRP.
    """
    session = stub_sessions.get(booking_reference)
    if not session:
        raise HTTPException(status_code=404, detail="Booking reference not found in stub engine.")

    callback_base = session.get("webhook_callback_url", DEFAULT_SRP_WEBHOOK_BASE).rstrip("/")
    url = f"{callback_base}/link-ready"

    payload = {
        "booking_reference": booking_reference,
        "exam_engine_session_ref": session["exam_engine_session_ref"],
        "assessment_link": session["assessment_link"],
        "link_status": "confirmed",
        "timestamp": datetime.utcnow().isoformat()
    }

    res = send_signed_webhook(url, payload)
    return {"webhook_status_code": res.status_code, "webhook_response": res.text}

@app.post("/api/v1/exam-engine/stub/trigger-result")
def trigger_result(req: TriggerResultRequest):
    """
    Pushes a rich realistic mock assessment result webhook back to SRP.
    """
    session = stub_sessions.get(req.booking_reference, {})
    session_ref = session.get("exam_engine_session_ref", f"EXM-SESS-{uuid.uuid4().hex[:8].upper()}")
    student_id = session.get("student_id", 1)
    subject_id = session.get("subject_id", 1)
    level = req.level or session.get("level", "District")

    callback_base = req.webhook_url or session.get("webhook_callback_url") or DEFAULT_SRP_WEBHOOK_BASE
    url = f"{callback_base.rstrip('/')}/result"

    # Generate realistic rich breakdown payloads
    topic_breakdown = [
        {"topic": "Core Conceptual Knowledge", "score": round(req.score * 0.98, 1), "total": 100},
        {"topic": "Practical Problem Solving", "score": round(req.score * 1.02, 1), "total": 100},
        {"topic": "Advanced Application & Edge Cases", "score": round(req.score, 1), "total": 100}
    ]

    correct_vs_selected = [
        {
            "question_id": 1,
            "question": "Which design pattern ensures a class has only one instance?",
            "selected": "Singleton",
            "correct": "Singleton",
            "is_correct": True
        },
        {
            "question_id": 2,
            "question": "What is the primary advantage of RESTful stateless APIs?",
            "selected": "Scalability across server clusters",
            "correct": "Scalability across server clusters",
            "is_correct": True
        },
        {
            "question_id": 3,
            "question": "In SQL transaction isolation, which anomaly does Repeatable Read prevent?",
            "selected": "Phantom Read" if req.score < 80 else "Non-repeatable Read",
            "correct": "Non-repeatable Read",
            "is_correct": (req.score >= 80)
        }
    ]

    payload = {
        "booking_reference": req.booking_reference,
        "exam_engine_session_ref": session_ref,
        "student_id": student_id,
        "subject_id": subject_id,
        "level": level,
        "score": req.score,
        "pass_fail": req.pass_fail,
        "topic_breakdown": topic_breakdown,
        "correct_vs_selected": correct_vs_selected,
        "timestamp": datetime.utcnow().isoformat()
    }

    res = send_signed_webhook(url, payload)
    return {
        "success": res.status_code in (200, 201),
        "webhook_url": url,
        "status_code": res.status_code,
        "response": res.text,
        "payload_sent": payload
    }

def send_signed_webhook(url: str, payload: Dict[str, Any]):
    headers = {
        "Content-Type": "application/json",
        "X-Webhook-Secret": SRP_WEBHOOK_SECRET
    }
    logger.info(f"Sending signed webhook to SRP: POST {url}")
    return requests.post(url, json=payload, headers=headers, timeout=10)

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("EXAM_ENGINE_STUB_PORT", 8001))
    uvicorn.run("server:app", host="0.0.0.0", port=port, reload=True)
